apiVersion: v1.1 #Does this one need to be there?
resources:
#  - name: dtz_build_info
#    type: BuildInfo
#    configuration:
#     sourceArtifactory: Artifactory
#      buildName: Sandbox - DevOps Test Zone Stager - Generate Release Package
#      buildNumber: 1
  - name: release_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: DevOps_Test_Zone
      version: 1.0.1
  - name: signed_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: DevOps_Test_Zone
      version: 1.0.1
  - name: distribution_rules
    type: DistributionRule
    configuration:
      sourceDistribution: Distribution
      serviceName: Edge*
      siteName: Edge*
      cityName: '*'
      countryCodes:
        - '*'

pipelines:
  - name: createReleaseBundlePipeline
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: DevOps_Test_Zone
          releaseBundleVersion: 1.0.${res_dtz_build_info_buildNumber}
          dryRun: false
          sign: false
          description: Creating the Release Bundle
          inputResources:
            - name: dtz_build_info
              #trigger: true
              trigger: false
          outputResources:
            - name: release_bundle
  - name: sign
    type: SignReleaseBundle
    configuration:
      inputResources:
        - name: release_bundle
      outputResources:
        - name: signed_bundle
  - name: distribute
    type: DistributeReleaseBundle
    configuration:
      dryRun: false
      inputResources:
        - name: signed_bundle
        - name: distribution_rules
