apiVersion: v1.1 #Does this one need to be there?
resources:
  - name: dtz_build_info
    type: BuildInfo
    configuration:
     sourceArtifactory: Artifactory
      buildName: "Sandbox - DevOps Test Zone Stager - Generate Release Package"
      buildNumber: 1
  - name: johnc_release_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: DevOps_Test_Zone
      version: 1.0.1
  - name: johnc_signed_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: DevOps_Test_Zone
      version: 1.0.1
  - name: johnc_distribution_rules
    type: DistributionRule
    configuration:
      sourceDistribution: Distribution
      serviceName: Edge*
      siteName: Edge*
      cityName: '*'
      countryCodes:
        - '*'

pipelines:
  - name: createReleaseBundlePipeline
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: DevOps_Test_Zone
          releaseBundleVersion: 1.0.0
          dryRun: false
          sign: false
          description: Creating the Release Bundle
          inputResources:
            - name: dtz_build_info
              trigger: false
            #  trigger: false
          outputResources:
            - name: johnc_release_bundle
      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: johnc_release_bundle
          outputResources:
            - name: johnc_signed_bundle
      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          inputResources:
            - name: johnc_signed_bundle
            - name: johnc_distribution_rules
